In [10]:
import pandas as pd  # For data manipulation and analysis
import numpy as np   # For numerical operations

# For data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# For handling missing values
from sklearn.impute import SimpleImputer  # If using scikit-learn for imputation

In [12]:
df = pd.read_csv('/Users/eawe.fellow/Desktop/NYC Energy Consumption Data Sci Caostone/Data 2/raw/Electric_Consumption_And_Cost__2010_-_Feb_2023__20240417.csv')

/var/folders/yz/n572n2w51t30htrrgdgw384m0000gq/T/ipykernel_49056/151010280.py:1: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/eawe.fellow/Desktop/NYC Energy Consumption Data Sci Caostone/Data 2/raw/Electric_Consumption_And_Cost__2010_-_Feb_2023__20240417.csv')

In [13]:
df.isnull()

,Development Name,Borough,Account Name,Location,Meter AMR,Meter Scope,TDS #,EDP,RC Code,Funding Source,...,Meter Number,Estimated,Current Charges,Rate Class,Bill Analyzed,Consumption (KWH),KWH Charges,Consumption (KW),KW Charges,Other charges
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447844,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
447845,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
447846,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
447847,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
447848,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
print(df.info)

<bound method DataFrame.info of        Development Name   Borough     Account Name Location Meter AMR  \
0                 ADAMS     BRONX            ADAMS   BLD 05      NONE
1                 ADAMS     BRONX            ADAMS   BLD 05      NONE
2                 ADAMS     BRONX            ADAMS   BLD 05      NONE
3                 ADAMS     BRONX            ADAMS   BLD 05      NONE
4                 ADAMS     BRONX            ADAMS   BLD 05      NONE
...                 ...       ...              ...      ...       ...
447844  WYCKOFF GARDENS  BROOKLYN  WYCKOFF GARDENS   BLD 03  INTERVAL
447845  WYCKOFF GARDENS  BROOKLYN  WYCKOFF GARDENS   BLD 03  INTERVAL
447846  WYCKOFF GARDENS  BROOKLYN  WYCKOFF GARDENS   BLD 02       AMR
447847  WYCKOFF GARDENS  BROOKLYN  WYCKOFF GARDENS   BLD 03       AMR
447848  WYCKOFF GARDENS  BROOKLYN  WYCKOFF GARDENS   BLD 03       AMR

         Meter Scope  TDS #  EDP  RC Code Funding Source  ... Meter Number  \
0       BLD 01 to 07  118.0  248  B011800        FEDERAL  ...      7223256
1       BLD 01 to 07  118.0  248  B011800        FEDERAL  ...      7223256
2       BLD 01 to 07  118.0  248  B011800        FEDERAL  ...      7223256
3       BLD 01 to 07  118.0  248  B011800        FEDERAL  ...      7223256
4       BLD 01 to 07  118.0  248  B011800        FEDERAL  ...      7223256
...              ...    ...  ...      ...            ...  ...          ...
447844           NaN  163.0  272  K016300        FEDERAL  ...      1786584
447845           NaN  163.0  272  K016300        FEDERAL  ...      1786586
447846           NaN  163.0  272  K016300        FEDERAL  ...      2786583
447847           NaN  163.0  272  K016300        FEDERAL  ...      2786584
447848           NaN  163.0  272  K016300        FEDERAL  ...      2786586

       Estimated  Current Charges   Rate Class Bill Analyzed  \
0              N         15396.82  GOV/NYC/068           Yes
1              N         14556.34  GOV/NYC/068           Yes
2              N         13904.98  GOV/NYC/068           Yes
3              N         14764.04  GOV/NYC/068           Yes
4              N         13729.54  GOV/NYC/068           Yes
...          ...              ...          ...           ...
447844         N          3342.30  GOV/NYC/068           Yes
447845         N          3755.58  GOV/NYC/068           Yes
447846         N          9092.54  GOV/NYC/068           Yes
447847         N          9927.14  GOV/NYC/068           Yes
447848         N         10805.65  GOV/NYC/068           Yes

       Consumption (KWH)  KWH Charges Consumption (KW) KW Charges  \
0               128800.0      7387.97           216.00    2808.00
1               115200.0      6607.87           224.00    2912.00
2               103200.0      5919.55           216.00    2808.00
3               105600.0      6057.22           208.00    2704.00
4                97600.0      5598.34           216.00    2808.00
...                  ...          ...              ...        ...
447844               0.0         0.00           144.60    1590.60
447845               0.0         0.00           162.48    1787.28
447846           82800.0      4327.13             0.00       0.00
447847           90400.0      4724.31             0.00       0.00
447848           98400.0      5142.39             0.00       0.00

        Other charges
0             5200.85
1             5036.47
2             5177.43
3             6002.82
4             5323.20
...               ...
447844        1751.70
447845        1968.30
447846        4765.41
447847        5202.83
447848        5663.26

[447849 rows x 27 columns]>

In [17]:
df.head(5)

,Development Name,Borough,Account Name,Location,Meter AMR,Meter Scope,TDS #,EDP,RC Code,Funding Source,...,Meter Number,Estimated,Current Charges,Rate Class,Bill Analyzed,Consumption (KWH),KWH Charges,Consumption (KW),KW Charges,Other charges
0,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,248,B011800,FEDERAL,...,7223256,N,15396.82,GOV/NYC/068,Yes,128800.0,7387.97,216.0,2808.0,5200.85
1,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,248,B011800,FEDERAL,...,7223256,N,14556.34,GOV/NYC/068,Yes,115200.0,6607.87,224.0,2912.0,5036.47
2,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,248,B011800,FEDERAL,...,7223256,N,13904.98,GOV/NYC/068,Yes,103200.0,5919.55,216.0,2808.0,5177.43
3,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,248,B011800,FEDERAL,...,7223256,N,14764.04,GOV/NYC/068,Yes,105600.0,6057.22,208.0,2704.0,6002.82
4,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,248,B011800,FEDERAL,...,7223256,N,13729.54,GOV/NYC/068,Yes,97600.0,5598.34,216.0,2808.0,5323.20

In [18]:
df.columns

Index(['Development Name', 'Borough', 'Account Name', 'Location', 'Meter AMR',
       'Meter Scope', 'TDS #', 'EDP', 'RC Code', 'Funding Source', 'AMP #',
       'Vendor Name', 'UMIS BILL ID', 'Revenue Month', 'Service Start Date',
       'Service End Date', '# days', 'Meter Number', 'Estimated',
       'Current Charges', 'Rate Class', 'Bill Analyzed', 'Consumption (KWH)',
       'KWH Charges', 'Consumption (KW)', 'KW Charges', 'Other charges'],
      dtype='object')

In [22]:
new_df = df.drop(columns=['EDP', 'AMP #', 'RC Code', 'UMIS BILL ID'])
new_df

,Development Name,Borough,Account Name,Location,Meter AMR,Meter Scope,TDS #,Funding Source,Vendor Name,Revenue Month,...,Meter Number,Estimated,Current Charges,Rate Class,Bill Analyzed,Consumption (KWH),KWH Charges,Consumption (KW),KW Charges,Other charges
0,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,FEDERAL,NEW YORK POWER AUTHORITY,2010-01,...,7223256,N,15396.82,GOV/NYC/068,Yes,128800.0,7387.97,216.00,2808.00,5200.85
1,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,FEDERAL,NEW YORK POWER AUTHORITY,2010-02,...,7223256,N,14556.34,GOV/NYC/068,Yes,115200.0,6607.87,224.00,2912.00,5036.47
2,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,FEDERAL,NEW YORK POWER AUTHORITY,2010-03,...,7223256,N,13904.98,GOV/NYC/068,Yes,103200.0,5919.55,216.00,2808.00,5177.43
3,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,FEDERAL,NEW YORK POWER AUTHORITY,2010-04,...,7223256,N,14764.04,GOV/NYC/068,Yes,105600.0,6057.22,208.00,2704.00,6002.82
4,ADAMS,BRONX,ADAMS,BLD 05,NONE,BLD 01 to 07,118.0,FEDERAL,NEW YORK POWER AUTHORITY,2010-05,...,7223256,N,13729.54,GOV/NYC/068,Yes,97600.0,5598.34,216.00,2808.00,5323.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447844,WYCKOFF GARDENS,BROOKLYN,WYCKOFF GARDENS,BLD 03,INTERVAL,NaN,163.0,FEDERAL,NEW YORK POWER AUTHORITY,2023-01,...,1786584,N,3342.30,GOV/NYC/068,Yes,0.0,0.00,144.60,1590.60,1751.70
447845,WYCKOFF GARDENS,BROOKLYN,WYCKOFF GARDENS,BLD 03,INTERVAL,NaN,163.0,FEDERAL,NEW YORK POWER AUTHORITY,2023-01,...,1786586,N,3755.58,GOV/NYC/068,Yes,0.0,0.00,162.48,1787.28,1968.30
447846,WYCKOFF GARDENS,BROOKLYN,WYCKOFF GARDENS,BLD 02,AMR,NaN,163.0,FEDERAL,NEW YORK POWER AUTHORITY,2023-01,...,2786583,N,9092.54,GOV/NYC/068,Yes,82800.0,4327.13,0.00,0.00,4765.41
447847,WYCKOFF GARDENS,BROOKLYN,WYCKOFF GARDENS,BLD 03,AMR,NaN,163.0,FEDERAL,NEW YORK POWER AUTHORITY,2023-01,...,2786584,N,9927.14,GOV/NYC/068,Yes,90400.0,4724.31,0.00,0.00,5202.83
447848,WYCKOFF GARDENS,BROOKLYN,WYCKOFF GARDENS,BLD 03,AMR,NaN,163.0,FEDERAL,NEW YORK POWER AUTHORITY,2023-01,...,2786586,N,10805.65,GOV/NYC/068,Yes,98400.0,5142.39,0.00,0.00,5663.26

In [24]:
new_df.describe()

,TDS #,# days,Current Charges,Consumption (KWH),KWH Charges,Consumption (KW),KW Charges,Other charges
count,445111.000000,447841.000000,4.478490e+05,4.478490e+05,4.478490e+05,447849.000000,447849.000000,4.478490e+05
mean,117.512099,30.447960,4.277735e+03,3.115645e+04,1.431691e+03,63.944056,903.329622,1.942714e+03
std,128.881800,1.898483,8.071365e+03,4.896050e+04,3.468343e+03,627.156668,1567.021090,4.679456e+03
min,1.000000,1.000000,-1.068744e+04,0.000000e+00,0.000000e+00,0.000000,0.000000,-5.939643e+04
25%,33.000000,29.000000,6.275200e+02,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00
50%,64.000000,30.000000,2.313950e+03,1.340000e+04,5.664600e+02,23.940000,288.050000,9.768900e+02
75%,150.000000,32.000000,5.606110e+03,4.608000e+04,2.034260e+03,90.340000,1323.160000,2.822310e+03
max,582.000000,396.000000,3.551569e+06,1.779600e+06,1.652807e+06,329074.000000,137814.280000,1.898762e+06